repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    -   id: clang-format
    -   id: cpplint
        args: [
            '--filter=-legal/copyright, 
            -runtime/references' # Disable warning: 'Is this a non-const reference? If so, make const or use a pointer'
        ]
    -   id: cppcheck